### ISSUE TITLE
Feeds and questions

### ISSUE THREAD

**Issue by nolanzandi** [g00dL00Ks/nested_copy#1]
Create one feed of the questions and feeds that shows up mixed together (as previously mentioned).  I’ve gotten it working where I  get the questions first and then the feeds after, but not all in one

**Comment by nolanzandi** [comment]
@g00dL00Ks Could you show me a screenshot or a link to where you've gotten it to where you have the questions first and then the feeds after?
Could you also sketch out a little bit more of what you mean by wanting it all in one? Or will that be clear when I see the data in the feeds?

**Comment by g00dL00Ks** [comment]
Yes, I just updated git and heroku with the correct view. 
If you go to news on the top nav: http://insider.goodlooksco.com/feeds
you'll see there are news feeds at the top and then questions underneath (ignore the formatting)
I'd like them to be intermixed based on the date they were created.  you'll see in the control i tried a few different things including trying partials (those not in use are commented out)
Does that make sense?

**Comment by nolanzandi** [comment]
![image](https://cloud.githubusercontent.com/assets/2481116/12371582/8d9ae4f8-bbed-11e5-88e2-1562772eb621.png)

So I got the two objects populating together sorted by created date. I did change the styling because combining the two styles (one line per row for one, vs 3 tiles per row for the other) was making things fly off the page, but both questions and feeds can be styled separately.

I've pushed my code to my local branch: https://github.com/g00dL00Ks/nested_copy/tree/branch-nolan

Let me know if you would like me to work on styling/upgrading this page, to work on other tasks, or to merge my code with master. Sorry I don't commit to master quite as often as the rest. Because i'm on a windows computer I have to rebase off of master before I can merge because I have specific environment changes to work on Windows. It takes about an hour to merge my code into master and so I'll refrain from merging my code until you ask (which is no problem).

**Comment by g00dL00Ks** [comment]
Yeah! thank you!  If you can work on the favorites, that would be great.  I'll set-up an issue ticket.

Also, I do my development on windows - you should check out "command prompt with ruby on rails" it allows me to deploy to git and heroku very easily.  An hour sounds incredibly brutal!!

**Comment by nolanzandi** [comment]
Total hours so far on this project: 3

**Comment by g00dL00Ks** [comment]
Looks great
