### ISSUE TITLE
Do we need bcrypt-ruby?

### ISSUE THREAD

**Issue by g00dL00Ks** [g00dL00Ks/nested_copy#6]
Hi @nolanzandi 
I see you added the bcrypt-ruby gem.  It's causing all sorts of issues on my computer with installation.  Do we need it?

This is the error i'm getting and trying to implement the suggested changed
https://github.com/codahale/bcrypt-ruby/issues/116

C:\> cd (path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri
C:\(path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri> ruby extconf.rb
C:\(path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri> make
C:\(path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri> make install

But i'm having trouble figuring out what the "path to gems root" is.  is it specific to nested_copy or ruby in general?

thanks

**Comment by nolanzandi** [comment]
@g00dL00Ks No, that shouldn't have gone through. It's a dependency I need for my version of win64

**Comment by g00dL00Ks** [comment]
got it - i merged your branch so i could pull down the changes.  I'll delete it from master, so maybe you can branch again?  sorry for the pain

**Comment by nolanzandi** [comment]
Well you can unmerge using git reset, or if that's too fiddly just delete that line from your gemfile, bundle install and then push it to master since bcrypt ruby isn't necessary for the work I did.
